coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        enabled: no
 jobs:
  test:    
    steps:      
      - name: Download Scantist-Bom-Detect
        run: curl -s https://scripts.scantist.com/staging/scantist-bom-detect.jar --output scantist-bom-detect.jar
      
      - name: Upload to Scantist 
        env: # Setting the Token
          SCANTISTTOKEN: ${{secrets.SCANTISTTOKEN }}
          SCANTIST_IMPORT_URL : "https://github.com/test-zp/testp.git"
        run: java -jar scantist-bom-detect.jar
